# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://inparens.com
title: in parens
subtitle:
author: Matthew Bennett
simple_search: http://google.com/search

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
port: 4000
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: archive
markdown: rdiscount
pygments: false

paginate: 8 # Posts per page on the blog index
recent_posts: 5 # Posts in the sidebar Recent Posts section
